#config_version=5

mode:
  start_events: ball_started
  stop_events:
    - skill_success
    - skill_failed
  priority: 500

shots:
  skill_shot:
    switch: s_Roller_1000
   advance_events: mode_skill_shot_started


variable_player:
  skill_success:
    score: 5000 
    
state_machines:
  skill_shot_success:
    debug: true
    states:
      start:
        label: Skill shot ready
      success:
        label: Skill successful
        events_when_started: skill_success
      failed:
        label: Skill failed
        events_when_started: skill_failed
    transitions:
      - source: start
        target: success
        events: skill_shot_hit
      - source: start
        target: failed
        events: skill_shot_unlit_hit