#config_version=5

show_player:
  mode_attract_started: 
   attract_display_loop:
    speed: 1
   attract_light_show:
    speed: 25

# variable_player:
  # mode_attract_started:
    # rules:
      # int: 1
      # action: set_machine