#config_version=5
mode:
    start_events: ball_starting
    priority: 100


coil_player:
    Rollover_Nine_hit: c_Chime_2
    Advance_Bonus_hit: c_Chime_3
    Bumpers_hit: c_Chime_3
    
shots:
  shot_Target_1000:
    switch: s_Target_1000
  shot_Lane_Top_Left:
    switch: s_Lane_Top_Left
  shot_Lane_Top_Right:
    switch: s_Lane_Top_Right
  shot_Rollover_1:
    switch: s_Rollover_1
    profile: Rollover_Nine
    show_tokens:
      leds: l_Rollover_1
  shot_Rollover_2:
    switch: s_Rollover_2
    profile: Rollover_Nine
    show_tokens:
      leds: l_Rollover_2
  shot_Rollover_3:
    switch: s_Rollover_3
    profile: Rollover_Nine
    show_tokens:
      leds: l_Rollover_3
  shot_Rollover_4:
    switch: s_Rollover_4
    profile: Rollover_Nine
    show_tokens:
      leds: l_Rollover_4    
  shot_Rollover_5:
    switch: s_Rollover_5
    profile: Rollover_Nine
    show_tokens:
      leds: l_Rollover_5
  shot_Rollover_6:
    switch: s_Rollover_6
    profile: Rollover_Nine
    show_tokens:
      leds: l_Rollover_6
  shot_Rollover_7:
    switch: s_Rollover_7
    profile: Rollover_Nine
    show_tokens:
      leds: l_Rollover_7
  shot_Rollover_8:
    switch: s_Rollover_8
    profile: Rollover_Nine
    show_tokens:
      leds: l_Rollover_8
  shot_Rollover_9:
    switch: s_Rollover_9
    profile: Rollover_Nine
    show_tokens:
      leds: l_Rollover_9
  shot_Target_Adv_Bonus_Left_Bottom:
    switch: s_Target_Adv_Bonus_Left_Bottom 
  shot_Target_Adv_Bonus_Right_Top:
    switch: s_Target_Adv_Bonus_Right_Top 
  shot_Target_Adv_Bonus_Left_Top:
    switch: s_Target_Adv_Bonus_Left_Top
  shot_Rollover_1000:
    switch: s_Rollover_1000
    profile: Always_on
    show_tokens:
      leds: l_Rollover_1000
  shot_Left_Bumper:
    switch: s_Left_Bumper
    profile: Blink_when_hit
    show_tokens:
      leds: l_Left_Bumper
  shot_Right_Bumper:
    switch: s_Right_Bumper
    profile: Blink_when_hit
    show_tokens:
      leds: l_Right_Bumper
  shot_Top_Bumper:
    switch: s_Top_Bumper
    profile: Blink_when_hit
    show_tokens:
      leds: l_Top_Bumper
  shot_Inlane_Bottom:
    switch: s_Inlane_Bottom
    show_tokens:
  shot_Outlane_Right:
    switch: s_Outlane_Right
  shot_Outlane_Left:
    switch: s_Outlane_Left
  shot_Slingshot_Left:
    switch: s_Slingshot_Left
  shot_Slingshot_Right:
    switch: s_Slingshot_Right
    profile: Blink_when_hit
    show_tokens:
      leds: l_Slingshot_Right
      
shot_profiles:
  Rollover_Nine:
      states:
      - name: unlit
        show: on
      - name: hit
        show: off
  Always_on:
     states:
     - name: unlit
       show: on
  Blink_when_hit:
     states:
     - name: ready
       show: "shot_unlit_hit"
     - name: hit
       show: "shot_lit_hit"
     loop: true