#config_version=5


    
mode_settings:
  display_delay_ms: 1s
  hurry_up_delay_ms: 0
  bonus_entries:
    - event: Adv_Bonus
      score: 1000 * (current_player.Adv_Bonus) * (current_player.pf_multiplier)