#config_version=5

mode:
    start_events: mode_base_started{machine.rules==1}
    
slide_player:
  mode_classic_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: JOUEUR (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
        

variable_player:
    ball_started:
        Adv_Bonus:
          int: 1
          action: set
    Rollover_Nine_hit:
        score: 100
    Advance_Bonus_hit{current_player.Adv_Bonus<10}:
        Adv_Bonus: 1
    Advance_Bonus_hit:
        score: 150
    shot_Rollover_1000_hit:
        score: 1000
    Bumpers_hit:
        score: 100
    shot_Target_1000_hit:
        score: 1000
    Lanes_hit:
        score: 1000
    Top_Lanes_hit{current_player.Adv_Bonus<10}:
        Adv_Bonus: 1
    Top_Lanes_hit:
        score: 100
    Slingshots_hit:
        score: 10
        

shot_groups:
  Rollover_Nine:
    shots: shot_Rollover_1, shot_Rollover_2, shot_Rollover_3, shot_Rollover_4, shot_Rollover_5, shot_Rollover_6, shot_Rollover_7, shot_Rollover_8, shot_Rollover_9
    enable_events: ball_started
    reset_events: ball_ending, Rollover_Nine_complete
  Advance_Bonus:
    shots: shot_Target_Adv_Bonus_Left_Bottom, shot_Target_Adv_Bonus_Right_Top, shot_Target_Adv_Bonus_Left_Top
    enable_events: ball_started
    disable_events: ball_ending
  Bumpers:
    shots: shot_Left_Bumper, shot_Right_Bumper, shot_Top_Bumper
    enable_events: ball_started
    disable_events: ball_ending
  Lanes:
    shots: shot_Outlane_Left, shot_Outlane_Right, shot_Inlane_Bottom, shot_SPECIAL
    enable_events: ball_started
    disable_events: ball_ending
  Top_Lanes:
    shots: shot_Lane_Top_Left, shot_Lane_Top_Right
    enable_events: ball_started
    disable_events: ball_ending
  Slingshots:
    shots: shot_Slingshot_Left, shot_Slingshot_Right
    enable_events: ball_started
    disable_events: ball_ending
    

shows:
   shot_unlit_hit:
    - duration: 100ms      # this show step lasts 1s
      lights:
       (leds): black 
    - duration: -1      # this show step lasts 1s
      lights:
       (leds): white
   shot_lit_hit:
    - duration: 100ms      # this show step lasts 1s
      lights:
       (leds): black 
    - duration: -1      # this show step lasts 1s
      lights:
       (leds): white     

