#config_version=5

hardware:
    platform: opp
    driverboards: gen2

opp:
    ports: COM4, COM6, COM3, COM7, COM8, COM9
        
playfields:
    playfield:
        default_source_device: bd_drain
        tags: default

displays:
  window:
    width: 800
    height: 600

ball_devices:
    bd_drain:
        ball_switches: s_Drain
        eject_coil: c_Drain
        tags: drain, home, trough
        
modes:
    - base  
    - attract
    - bonus
    - led_bonus
    - ball_save
    - double_bonus
    - target_cards
    - tilt
    - switcher
    - switcher2
    - modern
    - classic

machine_vars:
  rules:
    initial_value: 1
    value_type: int
    
combo_switches:
  custom_events:
    switches_1: s_Flipper_Left_Bottom
    switches_2: s_Start_button
    hold_time: 5s
    events_when_both: time_to_change

timed_switches:
  game_cancel:
    switch_tags: start
    time: 5s
    events_when_active: end_game

switches:
 s_Target_J:
  number: 1-0-1
 s_Target_Q:
  number: 1-0-2
 s_Target_K:
  number: 1-0-3
 s_Tilt_playfield:
  number: 1-0-7
  tags: tilt_warning
 s_Flipper_Left_Bottom:
  number: 1-0-8
 s_Flipper_Left_Top:
  number: 1-0-9
 s_Flipper_Right_Bottom:
  number: 1-0-10
 s_Flipper_Right_Top:
  number: 1-0-11
 s_Slingshot_Left:
  number: 1-0-16
 s_Slingshot_Right:
  number: 1-0-17
 s_Drain:
  number: 1-0-18
 s_Outlane_Right:
  number: 1-0-31
 s_Inlane_Bottom:
  number: 1-0-30
 s_Rollover_9:
  number: 1-0-29
 s_Rollover_8:
  number: 1-0-28
 s_Rollover_7:
  number: 1-0-27
 s_Target_10:
  number: 1-0-26
 s_Target_Adv_Bonus_Left_Bottom:
  number: 1-0-25
 s_Outlane_Left:
  number: 1-0-24
 s_Rollover_6:
  number: 2-0-1
 s_Rollover_5:
  number: 2-0-2
 s_Rollover_4:
  number: 2-0-3
 s_Rollover_3:
  number: 2-0-5
 s_Rollover_2:
  number: 2-0-6
 s_Rollover_1:
  number: 2-0-7
 s_Left_Bumper:
  number: 2-0-8
 s_Right_Bumper:
  number: 2-0-9
 s_Top_Bumper:
  number: 2-0-10
 s_Target_1000:
  number: 2-0-16
 s_Lane_Top_Left:
  number: 2-0-17
 s_Lane_Top_Right:
  number: 2-0-18
 s_Rollover_1000:
  number: 2-0-19
 s_SPECIAL:
  number: 2-0-20
 s_Target_Adv_Bonus_Right_Top:
  number: 2-0-21
 s_Target_Adv_Bonus_Left_Top:
  number: 2-0-22
 s_Target_A:
  number: 2-0-23
 s_Chime_1:
  number: 3-0-8
 s_Chime_2:
  number: 3-0-9
 s_Chime_3:
  number: 3-0-10
 s_Knocker:
  number: 3-0-11
 s_Start_button:
  number: 3-0-24
  tags: start
 s_Tilt_Plumb:
  number: 3-0-25
  tags: tilt_warning
 s_Tilt_Roll:
  number: 3-0-26
  tags: tilt_warning
 s_score_1p_10:
  number: 4-0-16
 s_score_1p_100:
  number: 4-0-17
 s_score_1p_1k:
  number: 4-0-18
 s_score_1p_10k:
  number: 4-0-19
  type : NC
 s_score_3p_10:
  number: 4-0-24
 s_score_3p_100:
  number: 4-0-25
 s_score_3p_1k:
  number: 4-0-26
 s_score_3p_10k:
  number: 4-0-27
  type : NC
 s_score_2p_10:
  number: 5-0-8
 s_score_2p_100:
  number: 5-0-9
 s_score_2p_1k:
  number: 5-0-10
 s_score_2p_10k:
  number: 5-0-11
  type : NC
 s_score_4p_10:
  number: 5-0-24
 s_score_4p_100:
  number: 5-0-25
 s_score_4p_1k:
  number: 5-0-26
 s_score_4p_10k:
  number: 5-0-27
  type : NC

coils:
 c_Flipper_Left_Bottom:
  number: 1-0-4
  allow_enable: true
 c_Flipper_Left_Top:
  number: 1-0-5
  allow_enable: true
 c_Flipper_Right_Bottom:
  number: 1-0-6
  allow_enable: true
 c_Flipper_Right_Top:
  number: 1-0-7
  allow_enable: true
 c_Slingshot_Left:
  number: 1-0-8
  default_pulse_ms: 20
 c_Slingshot_Right:
  number: 1-0-9
  default_pulse_ms: 20
 c_Drain:
  number: 1-0-10
  default_pulse_ms: 60
 c_Left_Bumper:
  number: 2-0-4
  default_pulse_ms: 20
 c_Right_Bumper:
  number: 2-0-5
  default_pulse_ms: 20
 c_Top_Bumper:
  number: 2-0-6
  default_pulse_ms: 20
 c_Chime_1:
  number: 3-0-4
  default_pulse_ms: 20
 c_Chime_2:
  number: 3-0-5
  default_pulse_ms: 20
 c_Chime_3:
  number: 3-0-6
  default_pulse_ms: 20
 c_Knocker:
  number: 3-0-7
  default_pulse_ms: 20
 c_score_1p_10:
  number: 4-0-8
  default_pulse_ms: 20
 c_score_1p_100:
  number: 4-0-9
  default_pulse_ms: 20
 c_score_1p_1k:
  number: 4-0-10
  default_pulse_ms: 20
 c_score_1p_10k:
  number: 4-0-11
  default_pulse_ms: 20
 c_score_3p_10:
  number: 4-0-12
  default_pulse_ms: 20
 c_score_3p_100:
  number: 4-0-13
  default_pulse_ms: 20
 c_score_3p_1k:
  number: 4-0-14
  default_pulse_ms: 20
 c_score_3p_10k:
  number: 4-0-15
  default_pulse_ms: 20
 c_score_2p_10:
  number: 5-0-4
  default_pulse_ms: 20
 c_score_2p_100:
  number: 5-0-5
  default_pulse_ms: 20
 c_score_2p_1k:
  number: 5-0-6
  default_pulse_ms: 20
 c_score_2p_10k:
  number: 5-0-7
  default_pulse_ms: 20
 c_score_4p_10:
  number: 5-0-12
  default_pulse_ms: 20
 c_score_4p_100:
  number: 5-0-13
  default_pulse_ms: 20
 c_score_4p_1k:
  number: 5-0-14
  default_pulse_ms: 20
 c_score_4p_10k:
  number: 5-0-15
  default_pulse_ms: 20

autofire_coils:
  Slingshot_Left:
    coil: c_Slingshot_Left
    switch: s_Slingshot_Left
  Slingshot_Right:
    coil: c_Slingshot_Right
    switch: s_Slingshot_Right
  Left_Bumper:
    coil: c_Left_Bumper
    switch: s_Left_Bumper
  Right_Bumper:
    coil: c_Right_Bumper
    switch: s_Right_Bumper
  Top_Bumper:
    coil: c_Top_Bumper
    switch: s_Top_Bumper  
  
flippers: 
 Flipper_Left_Bottom:
  main_coil: c_Flipper_Left_Bottom
  activation_switch: s_Flipper_Left_Bottom
 Flipper_Right_Bottom:
  main_coil: c_Flipper_Right_Bottom
  activation_switch: s_Flipper_Right_Bottom
 Flipper_Left_Top:
  main_coil: c_Flipper_Left_Top
  activation_switch: s_Flipper_Left_Top
 Flipper_Right_Top:
  main_coil: c_Flipper_Right_Top
  activation_switch: s_Flipper_Right_Top


  
score_reels:
  score_1p_10k:
    coil_inc: c_score_1p_10k
    switch_0: s_score_1p_10k
    limit_hi: 9
    limit_lo: 0
  score_1p_1k:
    coil_inc: c_score_1p_1k
    switch_9: s_score_1p_1k
    limit_hi: 9
    limit_lo: 0
  score_1p_100:
    coil_inc: c_score_1p_100
    switch_9: s_score_1p_100
    limit_hi: 9
    limit_lo: 0
  score_1p_10:
    coil_inc: c_score_1p_10
    switch_9: s_score_1p_10
    limit_hi: 9
    limit_lo: 0
  score_2p_10k:
    coil_inc: c_score_2p_10k
    switch_0: s_score_2p_10k
    limit_hi: 9
    limit_lo: 0
  score_2p_1k:
    coil_inc: c_score_2p_1k
    switch_9: s_score_2p_1k
    limit_hi: 9
    limit_lo: 0
  score_2p_100:
    coil_inc: c_score_2p_100
    switch_9: s_score_2p_100
    limit_hi: 9
    limit_lo: 0
  score_2p_10:
    coil_inc: c_score_2p_10
    switch_9: s_score_2p_10
    limit_hi: 9
    limit_lo: 0
  score_3p_10k:
    coil_inc: c_score_3p_10k
    switch_0: s_score_3p_10k
    limit_hi: 9
    limit_lo: 0
  score_3p_1k:
    coil_inc: c_score_3p_1k
    switch_9: s_score_3p_1k
    limit_hi: 9
    limit_lo: 0
  score_3p_100:
    coil_inc: c_score_3p_100
    switch_9: s_score_3p_100
    limit_hi: 9
    limit_lo: 0
  score_3p_10:
    coil_inc: c_score_3p_10
    switch_9: s_score_3p_10
    limit_hi: 9
    limit_lo: 0
  score_4p_10k:
    coil_inc: c_score_4p_10k
    switch_0: s_score_4p_10k
    limit_hi: 9
    limit_lo: 0
  score_4p_1k:
    coil_inc: c_score_4p_1k
    switch_9: s_score_4p_1k
    limit_hi: 9
    limit_lo: 0
  score_4p_100:
    coil_inc: c_score_4p_100
    switch_9: s_score_4p_100
    limit_hi: 9
    limit_lo: 0
  score_4p_10:
    coil_inc: c_score_4p_10
    switch_9: s_score_4p_10
    limit_hi: 9
    limit_lo: 0
    
score_reel_groups:
  player1:
    reels: score_1p_10k, score_1p_1k, score_1p_100, score_1p_10, None
    tags: player1
    #chimes: c_Knocker, c_Chime_1, c_Chime_2, c_Chime_3, None
    lights_tag: player1
  player2:
    reels: score_2p_10k, score_2p_1k, score_2p_100, score_2p_10, None
    tags: player2
    #chimes: c_Knocker, c_Chime_1, c_Chime_2, c_Chime_3, None
    #lights_tag: player2
  player3:
    reels: score_3p_10k, score_3p_1k, score_3p_100, score_3p_10, None
    tags: player3
    #chimes: c_Knocker, c_Chime_1, c_Chime_2, c_Chime_3, None
    #lights_tag: player3
  player4:
    reels: score_4p_10k, score_4p_1k, score_4p_100, score_4p_10, None
    tags: player4
    #chimes: c_Knocker, c_Chime_1, c_Chime_2, c_Chime_3, None
    #lights_tag: player4

lights:
 l_TEMP:
  number: 6-0-9
  subtype: matrix
 l_Right_Bumper:
  number: 6-0-8
  subtype: matrix
 l_Triple_Bonus:
  number: 6-0-10
  subtype: matrix
 l_Double_Bonus:
  number: 6-0-12
  subtype: matrix
 l_Top_Bumper:
  number: 6-0-13
  subtype: matrix
 l_Left_Bumper:
  number: 6-0-14
  subtype: matrix
 l_Rollover_2:
  number: 6-0-15
  subtype: matrix
 l_EB_Lane:
  number: 6-0-16
  subtype: matrix
 l_Lane_Top_Right:
  number: 6-0-17
  subtype: matrix
 l_Rollover_8:
  number: 6-0-18
  subtype: matrix
 l_Slingshot_Right:
  number: 6-0-19
  subtype: matrix
 l_SPECIAL_Lane_2:
  number: 6-0-20
  subtype: matrix
 l_EB:
  number: 6-0-21
  subtype: matrix
 l_Rollover_6:
  number: 6-0-22
  subtype: matrix
 l_Rollover_9:
  number: 6-0-23
  subtype: matrix
 l_Rollover_3:
  number: 6-0-24
  subtype: matrix
 l_Rollover_1000:
  number: 6-0-25
  subtype: matrix
 l_Rollover_5:
  number: 6-0-26
  subtype: matrix
 l_SPECIAL:
  number: 6-0-27
  subtype: matrix
 l_Target_10:
  number: 6-0-28
  subtype: matrix
 l_Rollover_1:
  number: 6-0-29
  subtype: matrix
 l_Rollover_7:
  number: 6-0-30
  subtype: matrix
 l_Rollover_4:
  number: 6-0-31
  subtype: matrix
 l_Bonus_10000:
  default_on_color: white
  fade_ms: 5ms
  channels:
   green:
    - number: 6-0-0
   red:
    - number: 6-0-1
   blue:
    - number: 6-0-2
   white:
    - number: 6-0-3
 l_Bonus_9000:
  default_on_color: white
  fade_ms: 5ms
  channels:
   green:
    - number: 6-0-4
   red:
    - number: 6-0-5
   blue:
    - number: 6-0-6
   white:
    - number: 6-0-7
 l_Bonus_8000:
  default_on_color: white
  fade_ms: 5ms
  channels:
   green:
    - number: 6-0-8
   red:
    - number: 6-0-9
   blue:
    - number: 6-0-10
   white:
    - number: 6-0-11
 l_Bonus_7000:
  default_on_color: white
  fade_ms: 5ms
  channels:
   green:
    - number: 6-0-12
   red:
    - number: 6-0-13
   blue:
    - number: 6-0-14
   white:
    - number: 6-0-15
 l_Bonus_6000:
  default_on_color: white
  fade_ms: 5ms
  channels:
   green:
    - number: 6-0-16
   red:
    - number: 6-0-17
   blue:
    - number: 6-0-18
   white:
    - number: 6-0-19
 l_Bonus_5000:
  default_on_color: white
  fade_ms: 5ms
  channels:
   green:
    - number: 6-0-20
   red:
    - number: 6-0-21
   blue:
    - number: 6-0-22
   white:
    - number: 6-0-23
 l_Bonus_4000:
  default_on_color: white
  fade_ms: 5ms
  channels:
   green:
    - number: 6-0-24
   red:
    - number: 6-0-25
   blue:
    - number: 6-0-26
   white:
    - number: 6-0-27
 l_Bonus_3000:
  default_on_color: white
  fade_ms: 5ms
  channels:
   green:
    - number: 6-0-28
   red:
    - number: 6-0-29
   blue:
    - number: 6-0-30
   white:
    - number: 6-0-31
 l_Bonus_2000:
  default_on_color: white
  fade_ms: 5ms
  channels:
   green:
    - number: 6-0-32
   red:
    - number: 6-0-33
   blue:
    - number: 6-0-34
   white:
    - number: 6-0-35
 l_Bonus_1000:
  default_on_color: white
  fade_ms: 5ms
  channels:
   green:
    - number: 6-0-36
   red:
    - number: 6-0-37
   blue:
    - number: 6-0-38
   white:
    - number: 6-0-39