#config_version=5

mode:
  start_events: time_to_change{machine.rules==1}
  stop_events: ball_starting, mode_switcher_started
  game_mode: False
  priority: 200

variable_player:
  mode_switcher2_started:
    rules:
      int: 2
      action: set_machine

coil_player:
  mode_switcher2_started:
    c_Chime_1:
      action: pulse
      pulse_power: 1.0
    c_Chime_2:
      action: pulse
      pulse_power: 1.0
    c_Chime_3:
      action: pulse
      pulse_power: 1.0
    c_Knocker:
      action: pulse
      pulse_power: 1.0